shell bash

font_family          Fira Code Nerd Font
bold_font            auto
italic_font          auto
font_size            12.0

# Translucidez sexy
background_opacity   0.90

# Imagen de fondo (cambiá el path)
background_image     ~/puntofiles/wallpapers/dark.jpg
background_image_layout  tiled
background_image_alignment center
background_tint      0.8

# Suavizado de bordes
window_padding_width  12

# Redondeo de ventana
window_border_width   0
inactive_text_alpha   0.9

# Cursor vibe
cursor_shape          block
cursor_blink_interval 0.5
cursor_color          #ff00e6

# ----- Tema NEON/CYBERPUNK -----

foreground            #e6e6e6
background            #000000

selection_foreground  #000000
selection_background  #00ffc8

# Colores (Synthwave 84 vibe)
color0   #212121
color1   #ff006e
color2   #69ff66
color3   #ffbf00
color4   #00b4ff
color5   #de00ff
color6   #00fff0
color7   #e6e6e6

color8   #4a4a4a
color9   #ff4f9a
color10  #8aff80
color11  #ffd859
color12  #59c3ff
color13  #f36cff
color14  #82fff5
color15  #ffffff

# ----- Rendering -----
detect_urls yes
enable_audio_bell no
scrollback_lines 20000
kitty_mod ctrl+shift

# Anti-lag + smooth lines
repaint_delay 8
input_delay 2
sync_to_monitor yes

# ----- Keybinds power -----
map kitty_mod+c copy_to_clipboard
map kitty_mod+v paste_from_clipboard
map kitty_mod+t new_tab
map kitty_mod+w close_tab
map kitty_mod+enter new_window

# ----- Tabs estilo cyber -----
tab_bar_style powerline
tab_title_template "{index}: {title}"
active_tab_foreground #000000
active_tab_background #00ffc8
inactive_tab_background #111
inactive_tab_foreground #aaa
